// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * AcloudCompatibility says whether the acloud the GUI is running inside is
 * newer than the one the GUI was verified against.
 */
export class AcloudCompatibility {
    /**
     * Creates a new AcloudCompatibility instance.
     * @param {Partial<AcloudCompatibility>} [$$source = {}] - The source object to create the AcloudCompatibility.
     */
    constructor($$source = {}) {
        if (!("RunningVersion" in $$source)) {
            /**
             * RunningVersion is the acloud build this GUI is part of, empty in a
             * development build.
             * @member
             * @type {string}
             */
            this["RunningVersion"] = "";
        }
        if (!("VerifiedVersion" in $$source)) {
            /**
             * VerifiedVersion is VerifiedAgainstAcloudVersion, so the frontend keeps no
             * copy of its own.
             * @member
             * @type {string}
             */
            this["VerifiedVersion"] = "";
        }
        if (!("RunningVersionIsNewerThanVerified" in $$source)) {
            /**
             * RunningVersionIsNewerThanVerified is the only field the UI acts on.
             * @member
             * @type {boolean}
             */
            this["RunningVersionIsNewerThanVerified"] = false;
        }
        if (!("Explanation" in $$source)) {
            /**
             * Explanation is a ready-to-show sentence, empty when there is nothing to say.
             * @member
             * @type {string}
             */
            this["Explanation"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AcloudCompatibility instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AcloudCompatibility}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AcloudCompatibility(/** @type {Partial<AcloudCompatibility>} */($$parsedSource));
    }
}

/**
 * ImageEntry is a published playroom image: Name is the alias sent as --image,
 * Reference the full registry path shown beside it.
 */
export class ImageEntry {
    /**
     * Creates a new ImageEntry instance.
     * @param {Partial<ImageEntry>} [$$source = {}] - The source object to create the ImageEntry.
     */
    constructor($$source = {}) {
        if (!("Name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Name"] = "";
        }
        if (!("Reference" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Reference"] = "";
        }
        if (!("IsDefault" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["IsDefault"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ImageEntry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ImageEntry}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ImageEntry(/** @type {Partial<ImageEntry>} */($$parsedSource));
    }
}

/**
 * ToolStatus reports whether an external tool a playroom depends on is usable.
 */
export class ToolStatus {
    /**
     * Creates a new ToolStatus instance.
     * @param {Partial<ToolStatus>} [$$source = {}] - The source object to create the ToolStatus.
     */
    constructor($$source = {}) {
        if (!("Name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Name"] = "";
        }
        if (!("Command" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Command"] = "";
        }
        if (!("State" in $$source)) {
            /**
             * "installed" | "missing" | "unknown"
             * @member
             * @type {string}
             */
            this["State"] = "";
        }
        if (!("Path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Path"] = "";
        }
        if (!("Message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ToolStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ToolStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ToolStatus(/** @type {Partial<ToolStatus>} */($$parsedSource));
    }
}
