// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ConnectInput is what the GUI sends for `acloud playroom connect`.
 */
export class ConnectInput {
    /**
     * Creates a new ConnectInput instance.
     * @param {Partial<ConnectInput>} [$$source = {}] - The source object to create the ConnectInput.
     */
    constructor($$source = {}) {
        if (!("Name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Name"] = "";
        }
        if (!("Playhouse" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Playhouse"] = "";
        }
        if (!("User" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["User"] = "";
        }
        if (!("ForwardAgent" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ForwardAgent"] = false;
        }
        if (!("Tunnel" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["Tunnel"] = false;
        }
        if (!("ForceInstall" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ForceInstall"] = false;
        }
        if (!("Terminal" in $$source)) {
            /**
             * Terminal picks the emulator to open. Not a CLI flag.
             * @member
             * @type {string}
             */
            this["Terminal"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConnectInput instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ConnectInput}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ConnectInput(/** @type {Partial<ConnectInput>} */($$parsedSource));
    }
}

/**
 * CreateInput is what the GUI sends for `acloud playroom create`. A blank or
 * false field is omitted, except ReadOnly and Privileged; see the builder.
 */
export class CreateInput {
    /**
     * Creates a new CreateInput instance.
     * @param {Partial<CreateInput>} [$$source = {}] - The source object to create the CreateInput.
     */
    constructor($$source = {}) {
        if (!("Name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Name"] = "";
        }
        if (!("Playhouse" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Playhouse"] = "";
        }
        if (!("Image" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Image"] = "";
        }
        if (!("Storage" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Storage"] = "";
        }
        if (!("CPURequest" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["CPURequest"] = "";
        }
        if (!("CPULimit" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["CPULimit"] = "";
        }
        if (!("MemoryRequest" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["MemoryRequest"] = "";
        }
        if (!("MemoryLimit" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["MemoryLimit"] = "";
        }
        if (!("SSHKey" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["SSHKey"] = "";
        }
        if (!("EnvVars" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["EnvVars"] = [];
        }
        if (!("GitRepos" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["GitRepos"] = [];
        }
        if (!("Copies" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["Copies"] = [];
        }
        if (!("Ports" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["Ports"] = [];
        }
        if (!("ProxyGroup" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ProxyGroup"] = "";
        }
        if (!("Exposure" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Exposure"] = "";
        }
        if (!("Ephemeral" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["Ephemeral"] = false;
        }
        if (!("ReadOnly" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ReadOnly"] = false;
        }
        if (!("Privileged" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["Privileged"] = false;
        }
        if (!("NoWait" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["NoWait"] = false;
        }
        if (!("WaitTimeout" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["WaitTimeout"] = "";
        }
        if (!("ForceInstall" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ForceInstall"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CreateInput instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CreateInput}
     */
    static createFrom($$source = {}) {
        const $$createField9_0 = $$createType0;
        const $$createField10_0 = $$createType0;
        const $$createField11_0 = $$createType0;
        const $$createField12_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("EnvVars" in $$parsedSource) {
            $$parsedSource["EnvVars"] = $$createField9_0($$parsedSource["EnvVars"]);
        }
        if ("GitRepos" in $$parsedSource) {
            $$parsedSource["GitRepos"] = $$createField10_0($$parsedSource["GitRepos"]);
        }
        if ("Copies" in $$parsedSource) {
            $$parsedSource["Copies"] = $$createField11_0($$parsedSource["Copies"]);
        }
        if ("Ports" in $$parsedSource) {
            $$parsedSource["Ports"] = $$createField12_0($$parsedSource["Ports"]);
        }
        return new CreateInput(/** @type {Partial<CreateInput>} */($$parsedSource));
    }
}

/**
 * DefaultEntry describes one playroom default for the GUI's settings screen.
 * The field names match the JSON `playroom config view -o json` emits.
 */
export class DefaultEntry {
    /**
     * Creates a new DefaultEntry instance.
     * @param {Partial<DefaultEntry>} [$$source = {}] - The source object to create the DefaultEntry.
     */
    constructor($$source = {}) {
        if (!("Key" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Key"] = "";
        }
        if (!("Value" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Value"] = "";
        }
        if (!("Source" in $$source)) {
            /**
             * "config" | "cache" | "built-in"
             * @member
             * @type {string}
             */
            this["Source"] = "";
        }
        if (!("Builtin" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Builtin"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DefaultEntry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DefaultEntry}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DefaultEntry(/** @type {Partial<DefaultEntry>} */($$parsedSource));
    }
}

/**
 * DeleteInput is what the GUI sends for `acloud playroom delete`.
 */
export class DeleteInput {
    /**
     * Creates a new DeleteInput instance.
     * @param {Partial<DeleteInput>} [$$source = {}] - The source object to create the DeleteInput.
     */
    constructor($$source = {}) {
        if (!("Name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Name"] = "";
        }
        if (!("Playhouse" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Playhouse"] = "";
        }
        if (!("Force" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["Force"] = false;
        }
        if (!("NoWait" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["NoWait"] = false;
        }
        if (!("WaitTimeout" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["WaitTimeout"] = "";
        }
        if (!("ForceInstall" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ForceInstall"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DeleteInput instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DeleteInput}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DeleteInput(/** @type {Partial<DeleteInput>} */($$parsedSource));
    }
}

/**
 * ListInput is what the GUI sends for `acloud playroom list`.
 */
export class ListInput {
    /**
     * Creates a new ListInput instance.
     * @param {Partial<ListInput>} [$$source = {}] - The source object to create the ListInput.
     */
    constructor($$source = {}) {
        if (!("Playhouse" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Playhouse"] = "";
        }
        if (!("Mine" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["Mine"] = false;
        }
        if (!("ForceInstall" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ForceInstall"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ListInput instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ListInput}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ListInput(/** @type {Partial<ListInput>} */($$parsedSource));
    }
}

/**
 * Listing describes a single playroom as emitted by `acloud playroom list -o json`.
 */
export class Listing {
    /**
     * Creates a new Listing instance.
     * @param {Partial<Listing>} [$$source = {}] - The source object to create the Listing.
     */
    constructor($$source = {}) {
        if (!("Name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Name"] = "";
        }
        if (!("Owner" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Owner"] = "";
        }
        if (!("Status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Status"] = "";
        }
        if (!("Image" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Image"] = "";
        }
        if (!("SSHHost" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["SSHHost"] = "";
        }
        if (!("CreatedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["CreatedAt"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("CPURequest" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["CPURequest"] = "";
        }
        if (!("MemRequest" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["MemRequest"] = "";
        }
        if (!("CPULimit" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["CPULimit"] = "";
        }
        if (!("MemLimit" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["MemLimit"] = "";
        }
        if (!("DiskSize" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["DiskSize"] = "";
        }
        if (!("DiskType" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["DiskType"] = "";
        }
        if (!("System" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["System"] = "";
        }
        if (!("Ports" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Ports"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Listing instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Listing}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Listing(/** @type {Partial<Listing>} */($$parsedSource));
    }
}

/**
 * OpenInput is what the GUI sends for `acloud playroom open`.
 */
export class OpenInput {
    /**
     * Creates a new OpenInput instance.
     * @param {Partial<OpenInput>} [$$source = {}] - The source object to create the OpenInput.
     */
    constructor($$source = {}) {
        if (!("Name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Name"] = "";
        }
        if (!("Playhouse" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Playhouse"] = "";
        }
        if (!("Editor" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Editor"] = "";
        }
        if (!("Tunnel" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["Tunnel"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OpenInput instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {OpenInput}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new OpenInput(/** @type {Partial<OpenInput>} */($$parsedSource));
    }
}

/**
 * StartInput is what the GUI sends for `acloud playroom start`.
 */
export class StartInput {
    /**
     * Creates a new StartInput instance.
     * @param {Partial<StartInput>} [$$source = {}] - The source object to create the StartInput.
     */
    constructor($$source = {}) {
        if (!("Name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Name"] = "";
        }
        if (!("Playhouse" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Playhouse"] = "";
        }
        if (!("Force" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["Force"] = false;
        }
        if (!("NoWait" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["NoWait"] = false;
        }
        if (!("WaitTimeout" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["WaitTimeout"] = "";
        }
        if (!("ForceInstall" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ForceInstall"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StartInput instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {StartInput}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StartInput(/** @type {Partial<StartInput>} */($$parsedSource));
    }
}

/**
 * StopInput is what the GUI sends for `acloud playroom stop`.
 */
export class StopInput {
    /**
     * Creates a new StopInput instance.
     * @param {Partial<StopInput>} [$$source = {}] - The source object to create the StopInput.
     */
    constructor($$source = {}) {
        if (!("Name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Name"] = "";
        }
        if (!("Playhouse" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Playhouse"] = "";
        }
        if (!("Force" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["Force"] = false;
        }
        if (!("ForceInstall" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ForceInstall"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StopInput instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {StopInput}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StopInput(/** @type {Partial<StopInput>} */($$parsedSource));
    }
}

/**
 * UpdateInput is what the GUI sends for `acloud playroom update`, where an
 * omitted flag keeps the current value. Hence the Change* companions.
 */
export class UpdateInput {
    /**
     * Creates a new UpdateInput instance.
     * @param {Partial<UpdateInput>} [$$source = {}] - The source object to create the UpdateInput.
     */
    constructor($$source = {}) {
        if (!("Name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Name"] = "";
        }
        if (!("Playhouse" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Playhouse"] = "";
        }
        if (!("Image" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Image"] = "";
        }
        if (!("CPURequest" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["CPURequest"] = "";
        }
        if (!("CPULimit" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["CPULimit"] = "";
        }
        if (!("MemRequest" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["MemRequest"] = "";
        }
        if (!("MemLimit" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["MemLimit"] = "";
        }
        if (!("ChangeReadOnly" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ChangeReadOnly"] = false;
        }
        if (!("ReadOnly" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ReadOnly"] = false;
        }
        if (!("ChangePorts" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ChangePorts"] = false;
        }
        if (!("Ports" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["Ports"] = [];
        }
        if (!("Force" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["Force"] = false;
        }
        if (!("NoWait" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["NoWait"] = false;
        }
        if (!("WaitTimeout" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["WaitTimeout"] = "";
        }
        if (!("ForceInstall" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ForceInstall"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateInput instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {UpdateInput}
     */
    static createFrom($$source = {}) {
        const $$createField10_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Ports" in $$parsedSource) {
            $$parsedSource["Ports"] = $$createField10_0($$parsedSource["Ports"]);
        }
        return new UpdateInput(/** @type {Partial<UpdateInput>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
