// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * BinaryStatus is everything the settings screen needs to explain the current
 * state and everything the error surfaces need to offer a way out.
 */
export class BinaryStatus {
    /**
     * Creates a new BinaryStatus instance.
     * @param {Partial<BinaryStatus>} [$$source = {}] - The source object to create the BinaryStatus.
     */
    constructor($$source = {}) {
        if (!("Path" in $$source)) {
            /**
             * Path is the binary that will be executed, empty when none was found.
             * @member
             * @type {string}
             */
            this["Path"] = "";
        }
        if (!("Source" in $$source)) {
            /**
             * Source is one of the BinarySource constants.
             * @member
             * @type {string}
             */
            this["Source"] = "";
        }
        if (!("Found" in $$source)) {
            /**
             * Found reports whether Path can be executed at all.
             * @member
             * @type {boolean}
             */
            this["Found"] = false;
        }
        if (!("Version" in $$source)) {
            /**
             * Version is what `acloud version` reported, empty when it did not run.
             * @member
             * @type {string}
             */
            this["Version"] = "";
        }
        if (!("Message" in $$source)) {
            /**
             * Message is a ready-to-show sentence; empty when there is nothing to say.
             * @member
             * @type {string}
             */
            this["Message"] = "";
        }
        if (!("ConfiguredPath" in $$source)) {
            /**
             * ConfiguredPath is the path saved in the app, kept even when it no longer
             * works so the settings field can show what to correct.
             * @member
             * @type {string}
             */
            this["ConfiguredPath"] = "";
        }
        if (!("EnvironmentOverride" in $$source)) {
            /**
             * EnvironmentOverride reports that ACLOUD_BINARY is set, which outranks
             * ConfiguredPath. The UI disables its field and explains why.
             * @member
             * @type {boolean}
             */
            this["EnvironmentOverride"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BinaryStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BinaryStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BinaryStatus(/** @type {Partial<BinaryStatus>} */($$parsedSource));
    }
}
