// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * CloudAccountEntry is a cloud account from `cloud-accounts get -o json`.
 * Identity is the value --cloud-account expects; the rest is for display.
 */
export class CloudAccountEntry {
    /**
     * Creates a new CloudAccountEntry instance.
     * @param {Partial<CloudAccountEntry>} [$$source = {}] - The source object to create the CloudAccountEntry.
     */
    constructor($$source = {}) {
        if (!("Identity" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Identity"] = "";
        }
        if (!("DisplayName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["DisplayName"] = "";
        }
        if (!("Provider" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Provider"] = "";
        }
        if (!("Regions" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Regions"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CloudAccountEntry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CloudAccountEntry}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CloudAccountEntry(/** @type {Partial<CloudAccountEntry>} */($$parsedSource));
    }
}

/**
 * CreateInput is what the GUI sends for `acloud playhouse create`. A blank or
 * zero field is omitted, so the command's own default or inference applies.
 */
export class CreateInput {
    /**
     * Creates a new CreateInput instance.
     * @param {Partial<CreateInput>} [$$source = {}] - The source object to create the CreateInput.
     */
    constructor($$source = {}) {
        if (!("Name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Name"] = "";
        }
        if (!("CloudAccount" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["CloudAccount"] = "";
        }
        if (!("Region" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Region"] = "";
        }
        if (!("Environment" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Environment"] = "";
        }
        if (!("Version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Version"] = "";
        }
        if (!("UpdateChannel" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["UpdateChannel"] = "";
        }
        if (!("MaintenanceScheduleIdentity" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["MaintenanceScheduleIdentity"] = "";
        }
        if (!("NodeType" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["NodeType"] = "";
        }
        if (!("SystemNodeType" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["SystemNodeType"] = "";
        }
        if (!("PlayroomNodeType" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["PlayroomNodeType"] = "";
        }
        if (!("PrivilegedNodeType" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["PrivilegedNodeType"] = "";
        }
        if (!("NodeCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["NodeCount"] = 0;
        }
        if (!("MaxPlayroomNodes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["MaxPlayroomNodes"] = 0;
        }
        if (!("MaxPrivilegedNodes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["MaxPrivilegedNodes"] = 0;
        }
        if (!("Exposure" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Exposure"] = "";
        }
        if (!("TailscaleOAuthClientID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["TailscaleOAuthClientID"] = "";
        }
        if (!("TailscaleOAuthClientSecret" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["TailscaleOAuthClientSecret"] = "";
        }
        if (!("WaitTimeout" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["WaitTimeout"] = "";
        }
        if (!("NoDefault" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["NoDefault"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CreateInput instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CreateInput}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CreateInput(/** @type {Partial<CreateInput>} */($$parsedSource));
    }
}

/**
 * DeleteInput is what the GUI sends for `acloud playhouse delete`.
 */
export class DeleteInput {
    /**
     * Creates a new DeleteInput instance.
     * @param {Partial<DeleteInput>} [$$source = {}] - The source object to create the DeleteInput.
     */
    constructor($$source = {}) {
        if (!("Name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Name"] = "";
        }
        if (!("Force" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["Force"] = false;
        }
        if (!("NoWait" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["NoWait"] = false;
        }
        if (!("WaitTimeout" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["WaitTimeout"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DeleteInput instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DeleteInput}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DeleteInput(/** @type {Partial<DeleteInput>} */($$parsedSource));
    }
}

/**
 * EnvironmentEntry is an AME environment from `environments get -o json`. Slug
 * is the value sent as CreateInput.Environment; the rest is for display.
 */
export class EnvironmentEntry {
    /**
     * Creates a new EnvironmentEntry instance.
     * @param {Partial<EnvironmentEntry>} [$$source = {}] - The source object to create the EnvironmentEntry.
     */
    constructor($$source = {}) {
        if (!("Slug" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Slug"] = "";
        }
        if (!("Name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Name"] = "";
        }
        if (!("Description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Description"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EnvironmentEntry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {EnvironmentEntry}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new EnvironmentEntry(/** @type {Partial<EnvironmentEntry>} */($$parsedSource));
    }
}

/**
 * PlayhouseEntry is a slim view of a playhouse cluster for the GUI. The field
 * names match the JSON `playhouse list -o json` emits.
 */
export class PlayhouseEntry {
    /**
     * Creates a new PlayhouseEntry instance.
     * @param {Partial<PlayhouseEntry>} [$$source = {}] - The source object to create the PlayhouseEntry.
     */
    constructor($$source = {}) {
        if (!("Identity" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Identity"] = "";
        }
        if (!("Slug" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Slug"] = "";
        }
        if (!("Status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Status"] = "";
        }
        if (!("Region" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Region"] = "";
        }
        if (!("Version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Version"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PlayhouseEntry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PlayhouseEntry}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PlayhouseEntry(/** @type {Partial<PlayhouseEntry>} */($$parsedSource));
    }
}
