// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class ContextEntry {
    /**
     * Creates a new ContextEntry instance.
     * @param {Partial<ContextEntry>} [$$source = {}] - The source object to create the ContextEntry.
     */
    constructor($$source = {}) {
        if (!("Name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Name"] = "";
        }
        if (!("Organisation" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Organisation"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ContextEntry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ContextEntry}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ContextEntry(/** @type {Partial<ContextEntry>} */($$parsedSource));
    }
}

export class OrganisationEntry {
    /**
     * Creates a new OrganisationEntry instance.
     * @param {Partial<OrganisationEntry>} [$$source = {}] - The source object to create the OrganisationEntry.
     */
    constructor($$source = {}) {
        if (!("Slug" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Slug"] = "";
        }
        if (!("Name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OrganisationEntry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {OrganisationEntry}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new OrganisationEntry(/** @type {Partial<OrganisationEntry>} */($$parsedSource));
    }
}
