// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App exposes backend operations to the frontend through Wails bindings.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as cli$0 from "./backend/cli/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "./backend/config/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as local$0 from "./backend/local/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as playhouse$0 from "./backend/playhouse/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as playroom$0 from "./backend/playroom/models.js";

/**
 * BrowseForAcloudBinary opens a native file picker and returns the chosen path,
 * or "" when the user cancelled. Typing an absolute path into a text field is a
 * poor way to find a binary in a hidden directory, and /usr/local/bin and
 * /opt/homebrew/bin are both hidden in the Finder's default view.
 * @returns {$CancellablePromise<string>}
 */
export function BrowseForAcloudBinary() {
    return $Call.ByID(3766231709);
}

/**
 * CancelOperation reports whether a running command was found and cancelled.
 * @param {string} operationID
 * @returns {$CancellablePromise<boolean>}
 */
export function CancelOperation(operationID) {
    return $Call.ByID(975567466, operationID);
}

/**
 * ClearAcloudBinary forgets the saved path and searches again, for when acloud
 * has since been installed normally.
 * @returns {$CancellablePromise<cli$0.BinaryStatus>}
 */
export function ClearAcloudBinary() {
    return $Call.ByID(1638829581).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * ConnectPlayroom opens an external terminal, so it has no cancellable operation.
 * @param {playroom$0.ConnectInput} input
 * @returns {$CancellablePromise<void>}
 */
export function ConnectPlayroom(input) {
    return $Call.ByID(686553126, input);
}

/**
 * @param {string} operationID
 * @param {playhouse$0.CreateInput} input
 * @returns {$CancellablePromise<void>}
 */
export function CreatePlayhouse(operationID, input) {
    return $Call.ByID(2866553675, operationID, input);
}

/**
 * @param {string} operationID
 * @param {playroom$0.CreateInput} input
 * @returns {$CancellablePromise<void>}
 */
export function CreatePlayroom(operationID, input) {
    return $Call.ByID(4062171818, operationID, input);
}

/**
 * @param {string} operationID
 * @param {playhouse$0.DeleteInput} input
 * @returns {$CancellablePromise<void>}
 */
export function DeletePlayhouse(operationID, input) {
    return $Call.ByID(3899842358, operationID, input);
}

/**
 * @param {string} operationID
 * @param {playroom$0.DeleteInput} input
 * @returns {$CancellablePromise<void>}
 */
export function DeletePlayroom(operationID, input) {
    return $Call.ByID(1560842733, operationID, input);
}

/**
 * GetAcloudBinaryStatus describes the binary the app will run, why, and what to
 * do when there is none.
 * @returns {$CancellablePromise<cli$0.BinaryStatus>}
 */
export function GetAcloudBinaryStatus() {
    return $Call.ByID(298481226).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * GetAcloudCompatibility reports whether the installed acloud is newer than the
 * one this GUI was verified against, so the sidebar can say so.
 * @returns {$CancellablePromise<local$0.AcloudCompatibility>}
 */
export function GetAcloudCompatibility() {
    return $Call.ByID(137755711).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetAcloudVersion() {
    return $Call.ByID(1911126099);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetCachedPlayhouse() {
    return $Call.ByID(2861882043);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetCurrentContext() {
    return $Call.ByID(62355233);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetCurrentOrganisation() {
    return $Call.ByID(3788646844);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetCurrentUserEmail() {
    return $Call.ByID(1722528603);
}

/**
 * GetOperatingSystem lets the frontend account for native window controls.
 * @returns {$CancellablePromise<string>}
 */
export function GetOperatingSystem() {
    return $Call.ByID(3538473173);
}

/**
 * @returns {$CancellablePromise<playroom$0.DefaultEntry[]>}
 */
export function GetPlayroomDefaults() {
    return $Call.ByID(2266523266).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @returns {$CancellablePromise<local$0.ToolStatus[]>}
 */
export function GetToolStatuses() {
    return $Call.ByID(1175740481).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * IsLoggedIn checks the credentials stored in the CLI configuration.
 * @returns {$CancellablePromise<boolean>}
 */
export function IsLoggedIn() {
    return $Call.ByID(1072220022);
}

/**
 * @returns {$CancellablePromise<playhouse$0.CloudAccountEntry[]>}
 */
export function ListCloudAccounts() {
    return $Call.ByID(1866846424).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * @returns {$CancellablePromise<config$0.ContextEntry[]>}
 */
export function ListContexts() {
    return $Call.ByID(1996591047).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * @returns {$CancellablePromise<playhouse$0.EnvironmentEntry[]>}
 */
export function ListEnvironments() {
    return $Call.ByID(394294985).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType11($result);
    }));
}

/**
 * @returns {$CancellablePromise<config$0.OrganisationEntry[]>}
 */
export function ListOrganisations() {
    return $Call.ByID(90350162).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType13($result);
    }));
}

/**
 * @returns {$CancellablePromise<playhouse$0.PlayhouseEntry[]>}
 */
export function ListPlayhouses() {
    return $Call.ByID(2233888008).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType15($result);
    }));
}

/**
 * @returns {$CancellablePromise<local$0.ImageEntry[]>}
 */
export function ListPlayroomImages() {
    return $Call.ByID(3564697124).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType17($result);
    }));
}

/**
 * @param {playroom$0.ListInput} input
 * @returns {$CancellablePromise<playroom$0.Listing[]>}
 */
export function ListPlayrooms(input) {
    return $Call.ByID(1813849851, input).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType19($result);
    }));
}

/**
 * LoginWithTerminal starts interactive CLI login; the frontend polls IsLoggedIn.
 * @param {string} terminalName
 * @returns {$CancellablePromise<void>}
 */
export function LoginWithTerminal(terminalName) {
    return $Call.ByID(456906764, terminalName);
}

/**
 * @param {string} operationID
 * @returns {$CancellablePromise<void>}
 */
export function Logout(operationID) {
    return $Call.ByID(3315130241, operationID);
}

/**
 * @param {string} operationID
 * @param {playroom$0.OpenInput} input
 * @returns {$CancellablePromise<void>}
 */
export function OpenPlayroomInEditor(operationID, input) {
    return $Call.ByID(3756097372, operationID, input);
}

/**
 * @param {playroom$0.ConnectInput} input
 * @returns {$CancellablePromise<string[]>}
 */
export function PreviewConnectPlayroom(input) {
    return $Call.ByID(2452866108, input).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType20($result);
    }));
}

/**
 * @param {playhouse$0.CreateInput} input
 * @returns {$CancellablePromise<string[]>}
 */
export function PreviewCreatePlayhouse(input) {
    return $Call.ByID(3520130009, input).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType20($result);
    }));
}

/**
 * @param {playroom$0.CreateInput} input
 * @returns {$CancellablePromise<string[]>}
 */
export function PreviewCreatePlayroom(input) {
    return $Call.ByID(1511217160, input).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType20($result);
    }));
}

/**
 * @param {playhouse$0.DeleteInput} input
 * @returns {$CancellablePromise<string[]>}
 */
export function PreviewDeletePlayhouse(input) {
    return $Call.ByID(4046241956, input).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType20($result);
    }));
}

/**
 * @param {playroom$0.DeleteInput} input
 * @returns {$CancellablePromise<string[]>}
 */
export function PreviewDeletePlayroom(input) {
    return $Call.ByID(3324577475, input).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType20($result);
    }));
}

/**
 * @param {playroom$0.OpenInput} input
 * @returns {$CancellablePromise<string[]>}
 */
export function PreviewOpenPlayroomInEditor(input) {
    return $Call.ByID(2022753278, input).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType20($result);
    }));
}

/**
 * @param {playroom$0.UpdateInput} input
 * @returns {$CancellablePromise<string[]>}
 */
export function PreviewUpdatePlayroom(input) {
    return $Call.ByID(2213859593, input).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType20($result);
    }));
}

/**
 * SetAcloudBinary remembers a path for this and later launches, returning the
 * resulting status so the caller can render the outcome without a second call.
 * A path that does not run is rejected rather than saved.
 * @param {string} path
 * @returns {$CancellablePromise<cli$0.BinaryStatus>}
 */
export function SetAcloudBinary(path) {
    return $Call.ByID(1998400028, path).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} operationID
 * @param {string} key
 * @param {string} value
 * @returns {$CancellablePromise<void>}
 */
export function SetPlayroomDefault(operationID, key, value) {
    return $Call.ByID(4041755465, operationID, key, value);
}

/**
 * SetWindowTheme remembers the theme and matches the native window background.
 * @param {string} theme
 * @returns {$CancellablePromise<void>}
 */
export function SetWindowTheme(theme) {
    return $Call.ByID(1314355354, theme);
}

/**
 * @param {string} operationID
 * @param {playroom$0.StartInput} input
 * @returns {$CancellablePromise<void>}
 */
export function StartPlayroom(operationID, input) {
    return $Call.ByID(3968073316, operationID, input);
}

/**
 * @param {string} operationID
 * @param {playroom$0.StopInput} input
 * @returns {$CancellablePromise<void>}
 */
export function StopPlayroom(operationID, input) {
    return $Call.ByID(108029706, operationID, input);
}

/**
 * @param {string} operationID
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function SwitchContext(operationID, name) {
    return $Call.ByID(1292338854, operationID, name);
}

/**
 * @param {string} operationID
 * @param {string} slug
 * @returns {$CancellablePromise<void>}
 */
export function SwitchOrganisation(operationID, slug) {
    return $Call.ByID(4084700909, operationID, slug);
}

/**
 * @param {string} operationID
 * @returns {$CancellablePromise<void>}
 */
export function UnsetAllPlayroomDefaults(operationID) {
    return $Call.ByID(488423928, operationID);
}

/**
 * @param {string} operationID
 * @param {string} key
 * @returns {$CancellablePromise<void>}
 */
export function UnsetPlayroomDefault(operationID, key) {
    return $Call.ByID(1427111362, operationID, key);
}

/**
 * @param {string} operationID
 * @param {playroom$0.UpdateInput} input
 * @returns {$CancellablePromise<void>}
 */
export function UpdatePlayroom(operationID, input) {
    return $Call.ByID(3846851043, operationID, input);
}

// Private type creation functions
const $$createType0 = cli$0.BinaryStatus.createFrom;
const $$createType1 = local$0.AcloudCompatibility.createFrom;
const $$createType2 = playroom$0.DefaultEntry.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = local$0.ToolStatus.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = playhouse$0.CloudAccountEntry.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = config$0.ContextEntry.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = playhouse$0.EnvironmentEntry.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = config$0.OrganisationEntry.createFrom;
const $$createType13 = $Create.Array($$createType12);
const $$createType14 = playhouse$0.PlayhouseEntry.createFrom;
const $$createType15 = $Create.Array($$createType14);
const $$createType16 = local$0.ImageEntry.createFrom;
const $$createType17 = $Create.Array($$createType16);
const $$createType18 = playroom$0.Listing.createFrom;
const $$createType19 = $Create.Array($$createType18);
const $$createType20 = $Create.Array($Create.Any);
